version: '2'

services:
  mysqldb:
    container_name: mysql
    image: mysql/mysql-server:8.0.16-1.1.11
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/data/mysql:/var/lib/mysql
    - $PWD/my55.cnf:/etc/my.cnf
    - $PWD/temp_my.cnf.j2:/.my.cnf
    environment:
    - MYSQL_ROOT_PASSWORD=qazwsx
    - MYSQL_DATABASE=ec
    - MYSQL_USER=ecuser
    - MYSQL_PASSWORD=qazwsx
    - EXTRA_OPTS="--lower_case_table_names=1"
    - TZ=Asia/Taipei
#    network_mode:  "host"
    ports: 
     - "3306:3306" 
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
    - "27017:27017"    
    volumes:
    - $PWD/data/mongodb:/data/db
    environment:
    - MONGODB_DATABASE=ec
    - TZ=Asia/Taipei
#   network_mode:  "host"
# mac系統無法使用network host

  db2:
    container_name: db2
    image: store/ibmcorp/db2_developer_c:11.1.4.4-x86_64
    ports:
    - "50000:50000"
    - "55000:55000"    
    volumes:
    - $PWD/data/db2:/database
    environment:
    - LICENSE=accept
    - DB2INSTANCE=ctginst1
    - DB2INST1_PASSWORD=ctginst1
    - DBNAME=maxdb76
    - TZ=Asia/Taipei
    - BLU=false
    - ENABLE_ORACLE_COMPATIBILITY=false
    - UPDATEAVAIL=NO
    - TO_CREATE_SAMPLEDB=false
    - REPODB=true
    - IS_OSXFS=false
    - PERSISTENT_HOME=true
    - HADR_ENABLED=false
#   network_mode:  "host"
# mac系統無法使用network host

