version: '2'

services:
  mysqldb:
    container_name: mysql
    #image: mysql/mysql-server:8.0.16-1.1.11
    image: mysql/mysql-server:8.0.28
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/data/mysql:/var/lib/mysql
    - $PWD/my55.cnf:/etc/my.cnf
    - $PWD/temp_my.cnf.j2:/.my.cnf
    environment:
    - MYSQL_ROOT_PASSWORD=qazwsx
    - MYSQL_DATABASE=cga101g1
    - MYSQL_USER=tibame
    - MYSQL_PASSWORD=tibame
    - EXTRA_OPTS="--lower_case_table_names=1"
    - TZ=Asia/Taipei
    network_mode:  "host"
    #    ports: 
    # - "3306:3306" 

