version: '2'

services:
  mysqldb:
    container_name: mysql
#    restart: always
    image: mysql/mysql-server:5.7.22-1.1.5
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/data/mysql:/var/lib/mysql
    - $PWD/my55.cnf:/etc/my.cnf
    - $PWD/temp_my.cnf.j2:/.my.cnf
    environment:
    - MYSQL_ROOT_PASSWORD=qazwsx
    - MYSQL_DATABASE=ec
    - MYSQL_USER=ecuser
    - MYSQL_PASSWORD=qazwsx
    - EXTRA_OPTS="--lower_case_table_names=1"
    - TZ=Asia/Taipei
    ports: 
    - "3306:3306"
    - "49160:22"
    - "49161:80"
  mongodb:
    container_name: robert-mongodb
    restart: always
    image: mongo:latest
    ports:
    - "27017:27017"    
    volumes:
    - $PWD/data/mongodb:/data/db
    environment:
    - MONGODB_DATABASE=ec

   

